[package]
name = "Mosaic"
version = "1.0.0"
authors = []

[addresses]
mosaic = "0xbd80b9323fe0c5b2baa7220b1a980f5cc26f684d5a45fbffbd94e24de01cdb70" # porto testnet

[dependencies.AptosFramework]
git = "https://github.com/movementlabsxyz/aptos-core.git"
rev = "movement"
subdir = "aptos-move/framework/aptos-framework"